<?php
defined( 'ABSPATH' ) || exit;
$andiya_pg_prices  = current_user_can( 'apg_manage_prices' );
$andiya_pg_quotes  = current_user_can( 'apg_manage_quotes' );
$andiya_pg_history = current_user_can( 'apg_view_history' );
?>
<div class="wrap apg-admin" dir="rtl" id="apg-app">
<header class="apg-header"><div><p class="apg-eyebrow">Pricing Manager for WooCommerce</p><h1><?php esc_html_e( 'مدیریت قیمت ووکامرس', 'andiya-price-guard' ); ?></h1><p><?php esc_html_e( 'فروش کالاهای دارای قیمت معتبر؛ استعلام برای کالاهای نیازمند بررسی.', 'andiya-price-guard' ); ?></p></div><span class="apg-version"><?php esc_html_e( 'نسخه آزمایشی', 'andiya-price-guard' ); ?> <?php echo esc_html( APG_VERSION ); ?></span></header>
<div id="apg-status" role="status" aria-live="polite"></div>
<nav class="apg-tabs" aria-label="<?php esc_attr_e( 'بخش‌های مدیریت قیمت', 'andiya-price-guard' ); ?>"><button type="button" data-tab="desk"><?php esc_html_e( 'میز کار', 'andiya-price-guard' ); ?></button>
<?php
if ( $andiya_pg_prices ) :
	?>
	<button type="button" data-tab="prices"><?php esc_html_e( 'قیمت‌ها', 'andiya-price-guard' ); ?></button><button type="button" data-tab="groups"><?php esc_html_e( 'گروه‌های قیمت‌گذاری', 'andiya-price-guard' ); ?></button><button type="button" data-tab="sources"><?php esc_html_e( 'منابع اطلاعات', 'andiya-price-guard' ); ?></button><?php endif; ?>
	<?php
	if ( $andiya_pg_quotes ) :
		?>
	<button type="button" data-tab="quotes"><?php esc_html_e( 'استعلام‌ها', 'andiya-price-guard' ); ?></button><?php endif; ?>
	<?php
	if ( $andiya_pg_history || $andiya_pg_prices ) :
		?>
	<button type="button" data-tab="history"><?php esc_html_e( 'تاریخچه', 'andiya-price-guard' ); ?></button><?php endif; ?>
	<?php
	if ( $andiya_pg_prices ) :
		?>
	<button type="button" data-tab="settings"><?php esc_html_e( 'تنظیمات', 'andiya-price-guard' ); ?></button><?php endif; ?></nav>
<section data-screen="desk"><div class="apg-task-grid" id="apg-tasks"></div><div class="apg-card"><h2><?php esc_html_e( 'از کجا شروع کنم؟', 'andiya-price-guard' ); ?></h2><p><?php esc_html_e( 'برای تغییر قیمت از «قیمت‌ها» شروع کنید. انتخاب‌های پرتکرار را در «گروه‌های قیمت‌گذاری» ذخیره کنید. گروه، ترکیب فیلترهای کالاهاست و دسته‌بندی فروشگاه را تغییر نمی‌دهد. برای مدیریت شرایط بحرانی، دامنه و حالت فروش را در تنظیمات انتخاب کنید.', 'andiya-price-guard' ); ?></p><p><?php esc_html_e( 'استعلام، سفارش پرداخت‌شده نیست. مشتری پس از دریافت پیشنهاد معتبر، اطلاعات ارسال و پرداخت را در مسیر اصلی ووکامرس تکمیل می‌کند.', 'andiya-price-guard' ); ?></p></div><div class="apg-card" id="apg-recent-card" hidden><h2><?php esc_html_e( 'عملیات اخیر و کارهای ناتمام', 'andiya-price-guard' ); ?></h2><p><?php esc_html_e( 'گزارش را باز کنید؛ ادامه پردازش از همان عملیات انجام می‌شود و درصد دوباره روی قیمت اضافه نمی‌شود.', 'andiya-price-guard' ); ?></p><div id="apg-recent"></div></div><details class="apg-card"><summary><?php esc_html_e( 'سلامت فروشگاه و محدودیت‌های نسخه', 'andiya-price-guard' ); ?></summary><div id="apg-health"></div><p><?php esc_html_e( 'این نسخه کالاهای ساده و متغیر را مدیریت می‌کند. درگاه، قالب اختصاصی، ترب، چندارزی، باندل، اشتراک و بازار چندفروشنده به آزمون اتصال جدا نیاز دارند.', 'andiya-price-guard' ); ?></p></details></section>
<?php if ( $andiya_pg_prices ) : ?>
<section data-screen="prices" hidden><div class="apg-card"><h2><?php esc_html_e( 'تغییر گروهی قیمت', 'andiya-price-guard' ); ?></h2><ol class="apg-steps"><li><?php esc_html_e( '۱. انتخاب کالا و روش', 'andiya-price-guard' ); ?></li><li><?php esc_html_e( '۲. پیش‌نمایش و استثناها', 'andiya-price-guard' ); ?></li><li><?php esc_html_e( '۳. تأیید نهایی و اجرا', 'andiya-price-guard' ); ?></li></ol>
<form id="apg-pricing"><div class="apg-fields"><label><?php esc_html_e( 'گروه قیمت‌گذاری ذخیره‌شده', 'andiya-price-guard' ); ?><select name="group"><option value=""><?php esc_html_e( 'انتخاب دستی', 'andiya-price-guard' ); ?></option></select></label><label><?php esc_html_e( 'دسته‌بندی‌ها', 'andiya-price-guard' ); ?><select name="categories" multiple size="4"></select><small><?php esc_html_e( 'بدون انتخاب = تمام دسته‌ها؛ زیر‌دسته‌ها هم شامل می‌شوند.', 'andiya-price-guard' ); ?></small></label><label><?php esc_html_e( 'جست‌وجو در نام محصول', 'andiya-price-guard' ); ?><input name="search" maxlength="180" data-apg-name-search><small><?php esc_html_e( 'پیشنهاد زنده با دو حرف؛ انتخاب نام، فیلتر تمام محصولات منطبق است.', 'andiya-price-guard' ); ?></small></label><label><?php esc_html_e( 'منبع محصول', 'andiya-price-guard' ); ?><input name="source" placeholder="<?php esc_attr_e( 'مثلاً source:1 یا نام تأمین‌کننده', 'andiya-price-guard' ); ?>"></label></div><div class="apg-terms" id="apg-price-terms"></div><p class="apg-scope-summary" id="apg-scope-summary" role="status" aria-live="polite"></p>
<div class="apg-fields"><label><?php esc_html_e( 'روش تغییر', 'andiya-price-guard' ); ?><select name="kind"><option value="percent"><?php esc_html_e( 'درصد افزایش یا کاهش', 'andiya-price-guard' ); ?></option><option value="fixed"><?php esc_html_e( 'مبلغ افزایش یا کاهش', 'andiya-price-guard' ); ?></option><option value="set"><?php esc_html_e( 'قیمت ثابت', 'andiya-price-guard' ); ?></option><option value="state"><?php esc_html_e( 'تغییر وضعیت فروش', 'andiya-price-guard' ); ?></option><option value="confirm"><?php esc_html_e( 'تأیید قیمت فعلی', 'andiya-price-guard' ); ?></option></select></label><label class="apg-value-field"><?php esc_html_e( 'مقدار', 'andiya-price-guard' ); ?><input name="value" inputmode="decimal" value="20" required><small><?php esc_html_e( 'برای کاهش درصد یا مبلغ، عدد منفی وارد کنید.', 'andiya-price-guard' ); ?></small><small id="apg-method-hint"></small></label><label class="apg-state-field" hidden><?php esc_html_e( 'وضعیت جدید', 'andiya-price-guard' ); ?><select name="state"><option value="inherit"><?php esc_html_e( 'پیروی از تنظیمات', 'andiya-price-guard' ); ?></option><option value="buy"><?php esc_html_e( 'خرید با قیمت معتبر', 'andiya-price-guard' ); ?></option><option value="quote"><?php esc_html_e( 'استعلام', 'andiya-price-guard' ); ?></option><option value="stop"><?php esc_html_e( 'توقف فروش', 'andiya-price-guard' ); ?></option></select></label><label><?php esc_html_e( 'مدت اعتبار قیمت (ساعت)', 'andiya-price-guard' ); ?><input name="hours" type="number" value="0" min="0" max="8760"><small><?php esc_html_e( 'صفر = بدون انقضای زمانی؛ حالت اضطراری همچنان اعمال می‌شود.', 'andiya-price-guard' ); ?></small></label></div>
<details><summary><?php esc_html_e( 'گردکردن، تخفیف و مبنای محاسبه', 'andiya-price-guard' ); ?></summary><div class="apg-fields"><label><?php esc_html_e( 'مضرب گردکردن', 'andiya-price-guard' ); ?><input name="round" value="0" inputmode="decimal"></label><label><?php esc_html_e( 'روش گردکردن', 'andiya-price-guard' ); ?><select name="round_mode"><option value="up"><?php esc_html_e( 'رو به بالا', 'andiya-price-guard' ); ?></option><option value="down"><?php esc_html_e( 'رو به پایین', 'andiya-price-guard' ); ?></option><option value="nearest"><?php esc_html_e( 'نزدیک‌ترین مقدار', 'andiya-price-guard' ); ?></option></select></label><label><?php esc_html_e( 'کالاهای دارای قیمت ویژه', 'andiya-price-guard' ); ?><select name="sale"><option value="skip"><?php esc_html_e( 'کنار گذاشته شوند', 'andiya-price-guard' ); ?></option><option value="both"><?php esc_html_e( 'هر دو قیمت تغییر کنند', 'andiya-price-guard' ); ?></option><option value="ratio"><?php esc_html_e( 'نسبت تخفیف حفظ شود', 'andiya-price-guard' ); ?></option><option value="clear"><?php esc_html_e( 'قیمت ویژه حذف شود', 'andiya-price-guard' ); ?></option></select></label><label><?php esc_html_e( 'مبنا', 'andiya-price-guard' ); ?><select name="base_id"><option value="0"><?php esc_html_e( 'قیمت فعلی (عملیات یک‌باره)', 'andiya-price-guard' ); ?></option></select><small><?php esc_html_e( 'اصلاح عملیات قبلی، از مبنای اولیه محاسبه می‌شود؛ درصدها روی هم جمع نمی‌شوند.', 'andiya-price-guard' ); ?></small></label></div><label><input type="checkbox" name="include_excluded"><?php esc_html_e( 'این بار کالاهای مستثنا هم بررسی شوند', 'andiya-price-guard' ); ?></label></details>
<button type="submit" class="button button-primary"><?php esc_html_e( 'نمایش پیش‌نمایش', 'andiya-price-guard' ); ?></button></form></div><div id="apg-batch" class="apg-card" hidden>
<h2 id="apg-batch-title"><?php esc_html_e( 'پیش‌نمایش و نتیجه عملیات', 'andiya-price-guard' ); ?></h2>
<div id="apg-batch-summary"></div>
<div id="apg-progress" class="apg-progress" hidden><p id="apg-progress-label"></p><progress id="apg-progress-bar" max="1" value="0" aria-label="<?php esc_attr_e( 'پیشرفت پردازش عملیات', 'andiya-price-guard' ); ?>"></progress></div>
<div class="apg-actions apg-selection-actions"><button type="button" class="button" id="apg-select-page"><?php esc_html_e( 'انتخاب کالاهای آماده این صفحه', 'andiya-price-guard' ); ?></button><button type="button" class="button" id="apg-exclude-page"><?php esc_html_e( 'کنارگذاشتن کالاهای این صفحه', 'andiya-price-guard' ); ?></button><span id="apg-selection-note"></span></div>
<div class="apg-table-wrap"><table class="widefat striped" id="apg-batch-table"><thead><tr>
<th><?php esc_html_e( 'انتخاب', 'andiya-price-guard' ); ?></th><th><?php esc_html_e( 'کالا / SKU', 'andiya-price-guard' ); ?></th><th><?php esc_html_e( 'قبل از عملیات', 'andiya-price-guard' ); ?></th><th><?php esc_html_e( 'محاسبه‌شده', 'andiya-price-guard' ); ?></th><th><?php esc_html_e( 'تغییر قیمت عادی', 'andiya-price-guard' ); ?></th><th><?php esc_html_e( 'وضعیت / دلیل', 'andiya-price-guard' ); ?></th>
</tr></thead><tbody></tbody></table></div>
<div class="apg-actions"><button type="button" class="button" id="apg-batch-prev"><?php esc_html_e( 'قبلی', 'andiya-price-guard' ); ?></button><span id="apg-batch-page"></span><button type="button" class="button" id="apg-batch-next"><?php esc_html_e( 'بعدی', 'andiya-price-guard' ); ?></button></div>
<div class="apg-actions apg-batch-actions">
<button type="button" class="button button-primary" id="apg-apply"><?php esc_html_e( 'بررسی و تأیید نهایی', 'andiya-price-guard' ); ?></button>
<button type="button" class="button button-primary" id="apg-resume" hidden><?php esc_html_e( 'ادامه عملیات ناتمام', 'andiya-price-guard' ); ?></button>
<button type="button" class="button" id="apg-batch-refresh"><?php esc_html_e( 'تازه‌سازی گزارش', 'andiya-price-guard' ); ?></button>
<a class="button" id="apg-export" hidden><?php esc_html_e( 'دریافت گزارش CSV', 'andiya-price-guard' ); ?></a>
<button type="button" class="button" id="apg-cancel"><?php esc_html_e( 'توقف پردازش آینده', 'andiya-price-guard' ); ?></button>
<button type="button" class="button" id="apg-undo"><?php esc_html_e( 'بازگردانی همین عملیات', 'andiya-price-guard' ); ?></button>
<button type="button" class="button" id="apg-revise"><?php esc_html_e( 'اصلاح از مبنای اولیه', 'andiya-price-guard' ); ?></button>
</div>
<form id="apg-apply-review" class="apg-review" hidden aria-labelledby="apg-review-title">
<h3 id="apg-review-title"><?php esc_html_e( 'تأیید نهایی پیش از تغییر کالاها', 'andiya-price-guard' ); ?></h3><div id="apg-apply-summary"></div>
<label class="apg-check-row"><input name="confirmed" id="apg-apply-confirmed" type="checkbox" required><?php esc_html_e( 'کالاهای انتخاب‌شده، مبلغ‌ها و امکان تأمین را بررسی کرده‌ام.', 'andiya-price-guard' ); ?></label>
<div class="apg-actions"><button type="submit" class="button button-primary" id="apg-apply-confirm"><?php esc_html_e( 'تأیید و شروع تغییرات', 'andiya-price-guard' ); ?></button><button type="button" class="button" id="apg-review-close"><?php esc_html_e( 'بازگشت به پیش‌نمایش', 'andiya-price-guard' ); ?></button></div>
</form>
<p class="apg-help"><?php esc_html_e( 'قیمت محاسبه‌شده برای ردیف کنارگذاشته، ناموفق یا دارای تعارض، به معنی اعمال‌شدن نیست. گزارش CSV وضعیت هر ردیف را دارد؛ برای ورود قیمت از فایل نمونه بخش منابع استفاده کنید.', 'andiya-price-guard' ); ?></p>
<p class="apg-help"><?php esc_html_e( 'بازگردانی، تغییر دستی جدید را حفظ می‌کند. توقف پردازش فقط ادامه کار را قطع می‌کند و تغییرهای انجام‌شده را برنمی‌گرداند.', 'andiya-price-guard' ); ?></p>
</div>
<div class="apg-card"><h2><?php esc_html_e( 'بررسی یک کالا یا تنوع', 'andiya-price-guard' ); ?></h2><form id="apg-search"><label><?php esc_html_e( 'نام یا SKU', 'andiya-price-guard' ); ?><input name="search" type="search" maxlength="180" autocomplete="off" aria-describedby="apg-product-search-status"></label><button class="button" type="submit"><?php esc_html_e( 'جست‌وجو', 'andiya-price-guard' ); ?></button></form><p id="apg-product-search-status" class="apg-help" role="status" aria-live="polite"></p><div id="apg-products"></div><div class="apg-actions"><button class="button" id="apg-product-prev" type="button"><?php esc_html_e( 'قبلی', 'andiya-price-guard' ); ?></button><span id="apg-product-page"></span><button class="button" id="apg-product-next" type="button"><?php esc_html_e( 'بعدی', 'andiya-price-guard' ); ?></button></div></div></section>
<section data-screen="groups" hidden>
<div class="apg-card apg-group-intro"><h2><?php esc_html_e( 'گروه‌های قیمت‌گذاری', 'andiya-price-guard' ); ?></h2>
<p><?php esc_html_e( 'دسته‌بندی، ساختار فروشگاه برای مشتری است. گروه قیمت‌گذاری یک انتخاب ذخیره‌شده برای کارهای مدیریتی است؛ مثلاً دسته «ساعت زنانه» همراه برند «سیکو». ساخت گروه اختیاری است.', 'andiya-price-guard' ); ?></p>
<p class="apg-help"><?php esc_html_e( 'گزینه‌های داخل یک فیلتر با «یا» و فیلترهای مختلف با «و» ترکیب می‌شوند. ساخت یا حذف گروه، دسته‌بندی و قیمت محصولات را تغییر نمی‌دهد.', 'andiya-price-guard' ); ?></p>
<button class="button" type="button" id="apg-groups-refresh"><?php esc_html_e( 'تازه‌سازی فهرست گروه‌ها', 'andiya-price-guard' ); ?></button><div id="apg-groups"></div></div>
<div class="apg-card"><h2 id="apg-group-title"><?php esc_html_e( 'ساخت گروه قیمت‌گذاری', 'andiya-price-guard' ); ?></h2>
<form id="apg-group"><input name="id" type="hidden"><input name="revision" type="hidden">
<div class="apg-fields"><label><?php esc_html_e( 'نام قابل تشخیص گروه', 'andiya-price-guard' ); ?><input name="name" required maxlength="180" placeholder="<?php esc_attr_e( 'مثلاً سیکو زنانه وارداتی', 'andiya-price-guard' ); ?>"></label><label><?php esc_html_e( 'دسته‌بندی‌ها', 'andiya-price-guard' ); ?><select name="categories" multiple size="4"></select><small><?php esc_html_e( 'زیر‌دسته‌ها هم شامل می‌شوند؛ بدون انتخاب یعنی همه دسته‌ها.', 'andiya-price-guard' ); ?></small></label><label><?php esc_html_e( 'جست‌وجو در نام کالا', 'andiya-price-guard' ); ?><input name="search" maxlength="180" data-apg-name-search><small><?php esc_html_e( 'پیشنهاد زنده با دو حرف؛ تمام محصولات منطبق با این عبارت در گروه قرار می‌گیرند.', 'andiya-price-guard' ); ?></small></label><label><?php esc_html_e( 'منبع کالا', 'andiya-price-guard' ); ?><input name="source"></label></div>
<div id="apg-group-terms" class="apg-terms"></div><p id="apg-group-scope" class="apg-scope-summary" role="status" aria-live="polite"></p>
<div class="apg-actions"><button class="button button-primary" type="submit"><?php esc_html_e( 'ذخیره گروه قیمت‌گذاری', 'andiya-price-guard' ); ?></button><button class="button" type="reset"><?php esc_html_e( 'ساخت گروه جدید', 'andiya-price-guard' ); ?></button></div>
</form></div></section>
<section data-screen="sources" hidden><div class="apg-card"><h2><?php esc_html_e( 'ورود فایل قیمت', 'andiya-price-guard' ); ?></h2><p><?php esc_html_e( 'SKU دقیق کالا یا تنوع، واحد پول و نام ستون‌ها را مشخص کنید. موجودی از این فایل تغییر نمی‌کند. کدهای دارای صفر اول را در اکسل به صورت متن ذخیره کنید.', 'andiya-price-guard' ); ?></p><form id="apg-import"><div class="apg-fields"><label><?php esc_html_e( 'فایل CSV یا XLSX', 'andiya-price-guard' ); ?><input name="file" type="file" accept=".csv,.xlsx" required></label><label><?php esc_html_e( 'واحد پول فایل', 'andiya-price-guard' ); ?><select name="currency" class="apg-currencies"></select></label><label><?php esc_html_e( 'ستون شناسه کالا', 'andiya-price-guard' ); ?><input name="sku_column" value="sku" required></label><label><?php esc_html_e( 'ستون قیمت عادی', 'andiya-price-guard' ); ?><input name="price_column" value="regular_price" required></label><label><?php esc_html_e( 'ستون قیمت ویژه', 'andiya-price-guard' ); ?><input name="sale_column" value="sale_price"></label><label><?php esc_html_e( 'اعتبار (ساعت)', 'andiya-price-guard' ); ?><input name="hours" type="number" min="0" value="0"></label></div><button class="button button-primary" type="submit"><?php esc_html_e( 'بررسی فایل و پیش‌نمایش', 'andiya-price-guard' ); ?></button></form><p><?php esc_html_e( 'حداکثر ۵ مگابایت؛ XLSX بدون فرمول، ماکرو و لینک خارجی. قیمت خالی نادیده گرفته می‌شود؛ قیمت صفر یا منفی رد می‌شود.', 'andiya-price-guard' ); ?></p><a href="<?php echo esc_url( APG_URL . 'sample-prices.csv' ); ?>" download><?php esc_html_e( 'دانلود فایل نمونه', 'andiya-price-guard' ); ?></a></div>
<div class="apg-card"><h2><?php esc_html_e( 'منبع JSON تأمین‌کننده', 'andiya-price-guard' ); ?></h2><p><?php esc_html_e( 'خودکارسازی به منبع واقعی نیاز دارد. ابتدا دریافت دستی، پیش‌نمایش و تخصیص کالاها به منبع را انجام دهید؛ سپس زمان‌بندی را فعال کنید.', 'andiya-price-guard' ); ?></p><form id="apg-source"><input name="id" type="hidden"><div class="apg-fields"><label><?php esc_html_e( 'نام منبع', 'andiya-price-guard' ); ?><input name="name" required></label><label><?php esc_html_e( 'نشانی عمومی HTTPS', 'andiya-price-guard' ); ?><input name="url" type="url" required dir="ltr"></label><label><?php esc_html_e( 'واحد پول', 'andiya-price-guard' ); ?><select name="currency" class="apg-currencies"></select></label><label><?php esc_html_e( 'فاصله دریافت و اعتبار (ساعت)', 'andiya-price-guard' ); ?><input name="hours" type="number" min="1" max="168" value="6"></label><label><?php esc_html_e( 'حد تغییر خودکار مجاز (%)', 'andiya-price-guard' ); ?><input name="threshold" value="20" inputmode="decimal"></label></div><label><input name="automatic" type="checkbox"><?php esc_html_e( 'دریافت زمان‌بندی‌شده برای کالاهای متصل به همین منبع', 'andiya-price-guard' ); ?></label><label><input name="consent" type="checkbox" required><?php esc_html_e( 'اتصال این فروشگاه به نشانی بالا را تأیید می‌کنم.', 'andiya-price-guard' ); ?></label><button class="button button-primary" type="submit"><?php esc_html_e( 'ذخیره منبع', 'andiya-price-guard' ); ?></button><button class="button" type="reset"><?php esc_html_e( 'منبع جدید', 'andiya-price-guard' ); ?></button></form><div id="apg-sources"></div><details><summary><?php esc_html_e( 'قالب داده و اتصال امن', 'andiya-price-guard' ); ?></summary><pre dir="ltr">{"currency":"IRT","updated_at":"2026-10-05T10:00:00Z","products":[{"sku":"001-A","regular_price":"12000000"}]}</pre><p><?php esc_html_e( 'زمان داده باید تازه باشد. جهش خارج از آستانه، قیمت قبلی را نگه می‌دارد و کالا را استعلامی می‌کند. کلید خصوصی در پایگاه داده ذخیره نمی‌شود؛ در wp-config.php از APG_SOURCE_TOKEN_شماره‌منبع استفاده کنید. اتصال ERP و پیامک، رابط توسعه بعدی است.', 'andiya-price-guard' ); ?></p></details></div></section>
<section data-screen="settings" hidden><form id="apg-settings"><div class="apg-card"><h2><?php esc_html_e( 'کنترل فروش در شرایط نوسان', 'andiya-price-guard' ); ?></h2><div class="apg-fields"><label><?php esc_html_e( 'حالت فروش', 'andiya-price-guard' ); ?><select name="mode"><option value="normal"><?php esc_html_e( 'عادی، با کنترل اعتبار هر کالا', 'andiya-price-guard' ); ?></option><option value="quote"><?php esc_html_e( 'حالت اضطراری: استعلام', 'andiya-price-guard' ); ?></option><option value="stop"><?php esc_html_e( 'توقف فروش و استعلام جدید', 'andiya-price-guard' ); ?></option></select></label><label><?php esc_html_e( 'دامنه کنترل', 'andiya-price-guard' ); ?><select name="categories" multiple size="4"></select><small><?php esc_html_e( 'بدون انتخاب = تمام فروشگاه؛ زیر‌دسته‌ها هم شامل‌اند.', 'andiya-price-guard' ); ?></small></label><label><?php esc_html_e( 'اعتبار پیش‌فرض قیمت (ساعت)', 'andiya-price-guard' ); ?><input name="valid_hours" type="number" min="0" max="8760" value="0"><small><?php esc_html_e( 'با عدد مثبت، کالاهای تأییدنشده نیز استعلامی می‌شوند.', 'andiya-price-guard' ); ?></small></label><label><?php esc_html_e( 'اعتبار پیش‌فرض پیشنهاد (ساعت)', 'andiya-price-guard' ); ?><input name="offer_hours" type="number" min="1" max="720" value="24"></label></div><p><?php esc_html_e( 'حالت استعلام، پیشنهادهای معتبر صادرشده را لغو نمی‌کند. حالت توقف، پذیرش پیشنهاد جدید را هم می‌بندد. سفارش پرداخت‌شده و تلاش پرداخت شروع‌شده با مبلغ ثبت‌شده ادامه می‌یابد.', 'andiya-price-guard' ); ?></p></div>
<div class="apg-card"><h2><?php esc_html_e( 'هنگام غیرفعال‌سازی افزونه', 'andiya-price-guard' ); ?></h2><label><input type="radio" name="deactivation" value="restore" checked><?php esc_html_e( 'بازگرداندن تغییرهای افزونه به مقدار قبلی (پیش‌فرض)', 'andiya-price-guard' ); ?></label><label><input type="radio" name="deactivation" value="keep"><?php esc_html_e( 'نگه‌داشتن قیمت‌های فعلی', 'andiya-price-guard' ); ?></label><p><?php esc_html_e( 'ویرایش دستی جدید، موجودی واقعی، سفارش‌ها و درخواست‌ها حفظ می‌شوند. کنترل نمایش افزونه حذف و حالت اضطراری بازنشانی می‌شود. افزونه‌های کش یا CDN باید محتوای فروشگاه را دوباره تازه کنند.', 'andiya-price-guard' ); ?></p><button class="button" type="button" id="apg-restore"><?php esc_html_e( 'تکمیل بازگردانی باقی‌مانده از غیرفعال‌سازی قبلی', 'andiya-price-guard' ); ?></button></div>
<details class="apg-card"><summary><?php esc_html_e( 'پیام‌ها، ایمیل و حریم خصوصی', 'andiya-price-guard' ); ?></summary><div class="apg-fields"><label><?php esc_html_e( 'متن دکمه استعلام', 'andiya-price-guard' ); ?><input name="label" required></label><label><?php esc_html_e( 'پیام استعلام', 'andiya-price-guard' ); ?><input name="message" required></label><label><?php esc_html_e( 'پیام توقف', 'andiya-price-guard' ); ?><input name="stop_message" required></label><label><?php esc_html_e( 'نگهداری درخواست‌های بسته (روز)', 'andiya-price-guard' ); ?><input name="retention" type="number" min="1" max="3650" value="90"></label></div><label><input name="email_admin" type="checkbox"><?php esc_html_e( 'ایمیل درخواست جدید به ایمیل مدیریت وردپرس', 'andiya-price-guard' ); ?></label><label><input name="email_customer" type="checkbox"><?php esc_html_e( 'ایمیل پیگیری و پیشنهاد به مشتری دارای ایمیل', 'andiya-price-guard' ); ?></label><label><input name="delete_data" type="checkbox"><?php esc_html_e( 'هنگام حذف کامل افزونه، اطلاعات اختصاصی آن پاک شود', 'andiya-price-guard' ); ?></label><p><?php esc_html_e( 'اطلاعات به آندیا ارسال نمی‌شود. درخواست‌های باز تا رسیدگی نگهداری می‌شوند. برای درخواست‌های بدون ایمیل، پس از احراز هویت مشتری از دکمه حذف اطلاعات شخصی در استعلام استفاده کنید.', 'andiya-price-guard' ); ?></p></details><button class="button button-primary" type="submit"><?php esc_html_e( 'بررسی تغییرات تنظیمات', 'andiya-price-guard' ); ?></button><div class="apg-card" id="apg-settings-review" hidden><h3><?php esc_html_e( 'تأیید نهایی تنظیمات', 'andiya-price-guard' ); ?></h3><p id="apg-settings-summary"></p><button class="button button-primary" type="button" id="apg-settings-save"><?php esc_html_e( 'تأیید و ذخیره تنظیمات', 'andiya-price-guard' ); ?></button></div></form></section>
<?php endif; ?>
<?php
if ( $andiya_pg_quotes ) :
	?>
	<section data-screen="quotes" hidden><div class="apg-card"><h2><?php esc_html_e( 'درخواست‌های استعلام', 'andiya-price-guard' ); ?></h2><button class="button" type="button" id="apg-quotes-refresh"><?php esc_html_e( 'تازه‌سازی', 'andiya-price-guard' ); ?></button><div id="apg-quotes"></div><div class="apg-actions"><button class="button" type="button" id="apg-quotes-prev"><?php esc_html_e( 'قبلی', 'andiya-price-guard' ); ?></button><span id="apg-quotes-page"></span><button class="button" type="button" id="apg-quotes-next"><?php esc_html_e( 'بعدی', 'andiya-price-guard' ); ?></button></div></div><div class="apg-card" id="apg-quote-detail" hidden></div></section><?php endif; ?>
<?php
if ( $andiya_pg_history || $andiya_pg_prices ) :
	?>
	<section data-screen="history" hidden><div class="apg-card"><h2><?php esc_html_e( 'عملیات و رویدادها', 'andiya-price-guard' ); ?></h2><button class="button" id="apg-history-refresh" type="button"><?php esc_html_e( 'تازه‌سازی', 'andiya-price-guard' ); ?></button><div id="apg-history"></div><div class="apg-actions"><button class="button" id="apg-history-prev" type="button"><?php esc_html_e( 'قبلی', 'andiya-price-guard' ); ?></button><span id="apg-history-page"></span><button class="button" id="apg-history-more" type="button"><?php esc_html_e( 'بعدی', 'andiya-price-guard' ); ?></button></div></div><div class="apg-card" id="apg-history-detail" hidden></div></section><?php endif; ?>
<dialog id="apg-product-dialog" dir="rtl" aria-labelledby="apg-product-title"><button class="apg-dialog-close button" type="button"><?php esc_html_e( 'بستن', 'andiya-price-guard' ); ?></button><h2 id="apg-product-title"></h2><form id="apg-product-form"><input name="id" type="hidden"><input name="fingerprint" type="hidden"><div class="apg-fields"><label class="apg-product-price"><?php esc_html_e( 'قیمت عادی', 'andiya-price-guard' ); ?><input name="regular_price" inputmode="decimal"></label><label class="apg-product-price"><?php esc_html_e( 'قیمت ویژه', 'andiya-price-guard' ); ?><input name="sale_price" inputmode="decimal"></label><label><?php esc_html_e( 'وضعیت', 'andiya-price-guard' ); ?><select name="state"><option value=""><?php esc_html_e( 'پیروی از تنظیمات', 'andiya-price-guard' ); ?></option><option value="buy"><?php esc_html_e( 'خرید با قیمت معتبر', 'andiya-price-guard' ); ?></option><option value="quote"><?php esc_html_e( 'استعلام', 'andiya-price-guard' ); ?></option><option value="stop"><?php esc_html_e( 'توقف فروش', 'andiya-price-guard' ); ?></option></select></label><label><?php esc_html_e( 'منبع', 'andiya-price-guard' ); ?><input name="source"></label><label><?php esc_html_e( 'اعتبار (ساعت)', 'andiya-price-guard' ); ?><input name="hours" type="number" min="0" value="0"></label></div><label><input name="exclude" type="checkbox"><?php esc_html_e( 'استثنا از تغییر گروهی و خودکار', 'andiya-price-guard' ); ?></label><label><input name="confirmed" type="checkbox"><?php esc_html_e( 'قیمت و امکان تأمین را بررسی کرده‌ام', 'andiya-price-guard' ); ?></label><p class="apg-product-error" role="alert"></p><button class="button button-primary" type="submit"><?php esc_html_e( 'ذخیره تغییرات', 'andiya-price-guard' ); ?></button></form><div id="apg-variations"></div></dialog>
</div>
